config/routes.rb
Rails.application.routes.draw do
  resources :tickets

  resources :stores

  resources :users

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  validates :person_cnt, presence: true
  
  belongs_to :user
  belongs_to :store
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :create, :show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token
  
    
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = get_current_user_ticket_list(@user)
  end
  
  def find_user_by_id(user_id)
    User.find(user_id)
  end
  
  def get_current_user_ticket_list (user)
    
    user_ticket_list = user.tickets
    
    ticket_list = []
    user_ticket_list.each do |user_ticket|
      ticket = TicketsHelper::Ticket.new
      ticket.store_id = user_ticket.store.id
      ticket.store_name = user_ticket.store.name
      ticket.reg_time = user_ticket.created_at
      ticket.wait_number = user_ticket.cnt
      ticket.wait_ahead_count = get_current_user_wait_ahead_count(user_ticket)
      ticket_list << ticket;
    end
    
    return ticket_list
  end
  
  
  def get_current_user_wait_ahead_count (user_ticket)
    all_waiting_users = get_store_all_waiting_users (user_ticket.store)
    calc_order_to_current_user user_ticket, all_waiting_users 
  end
  
  def get_store_all_waiting_users (store)
    store.tickets
  end
  
  def calc_order_to_current_user(user_ticket, all_waiting_users)
    all_waiting_users.where("id <= ?", user_ticket.id).count
  end
  

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    # user_id = params["user_id"]
    user_id = @user.id
    store_id = params["store_id"]
    
    @ticket = Ticket.new
    @ticket.user_id = user_id
    @ticket.store_id = store_id
    @ticket.cnt = get_new_ticket_number (store_id)

    respond_to do |format|
      if @ticket.save
        @newTicket = TicketsHelper::Ticket.new
        @newTicket.store_id = @ticket.store.id
        @newTicket.store_name = @ticket.store.name
        @newTicket.reg_time = @ticket.created_at
        @newTicket.wait_number = @ticket.cnt
        @newTicket.wait_ahead_count = get_current_user_wait_ahead_count(@ticket)
        
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show}
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def get_new_ticket_number (store_id)
    new_ticket_number = 0
    Store.transaction do
      store = Store.lock.find(store_id)
      new_ticket_number = store.cnt + 1
      store.cnt = new_ticket_number
      store.save!
    end
    
    return new_ticket_number
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end
    
    def set_user
      @user = User.find(1)
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:user_id, :store_id, :number, :person_cnt, :check_in)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  public class Ticket
    attr_accessor :store_id, :store_name, :wait_number, :wait_ahead_count, :reg_time
  
    def initialize (attributes = {})
      @store_id = attributes[:store_id]
      @store_name = attributes[:store_name]
      @wait_number = attributes[:number]
      @wait_ahead_count = attributes[:wait_count]
      @reg_time = attributes[:reg_time]
    end
  end
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :store_id %><br>
    <%= f.text_field :store_id %>
  </div>
  <div class="field">
    <%= f.label :cnt %><br>
    <%= f.number_field :cnt %>
  </div>
  <div class="field">
    <%= f.label :person_cnt %><br>
    <%= f.number_field :person_cnt %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <thead>
    <tr>
	  <th>상점 ID</th>
      <th>상점</th>
      <th>대기번호</th>
      <th>대기자수</th>
	  <th>접수시간</th>
	  <th>대기시간</th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_list.each do |ticket| %>
      <tr>
		<td><%= ticket.store_id %></td>
        <td><%= ticket.store_name %></td>
        <td><%= ticket.wait_number %></td>
        <td><%= ticket.wait_ahead_count %></td>
		<td><%= ticket.reg_time%>
		<td><%= distance_of_time_in_words(Time.now, ticket.reg_time)%>   
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @ticket.user_id %>
</p>

<p>
  <strong>Store:</strong>
  <%= @ticket.store_id %>
</p>

<p>
  <strong>Number:</strong>
  <%= @ticket.cnt %>
</p>

<p>
  <strong>Person cnt:</strong>
  <%= @ticket.person_cnt %>
</p>

<p>
  <strong>Check in:</strong>
  <%= @ticket.check_in %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>